### ISSUE TITLE
Provide this content on opensource.microsoft.com

### ISSUE THREAD

**Issue by Aaron-Junker** [microsoft/OSPO-Courses#11]
It would be cool to not have to navigate through a GitHuib repository for new Microsoft contributors. Adding these guides to opensource.microsoft.com would surely help.

**Comment by Aaron-Junker** [comment]
@emmairwin Thoughts?

**Comment by emmairwin** [comment]
Hi @Aaron-Junker 

The short answer is maybe.. but the longer answer is that most companies, organizations and non-profits have different Learning Management Systems.LMS (some formal institutions prefer open source solutions like Moodle, others like Mozilla use vendor solutions like Teachable, I have used Course in a Box (Github Pages) and still others have in-house platforms.  The reason I created this as a markdown course was so that, no matter the platform - if someone wanted to use this course, it would be super easy to cut and paste into that platform.

So that's the background on why Github.  I think having these on opensource.microsoft.com would be great, but would require design of a LMS-type delivery, and I am not sure that site is the right platform.  What is your vision for course content on opensource.microsoft.com ?

thanks for the question.

**Comment by Aaron-Junker** [comment]
> Hi @Aaron-Junker 
> 
> The short answer is maybe.. but the longer answer is that most companies, organizations and non-profits have different Learning Management Systems (LMS ) . Formal institutions prefer open source solutions like Moodle, others like Mozilla use simple vendor solutions like Teachable, I have used Course in a Box (Github Pages) and still others have in-house platforms.  The reason I created this as a markdown course was so that, no matter the platform - if someone wanted to use this course, it would be super easy to cut and paste into that platform.
> 
> So that's the background on why Github.  I think having these on opensource.microsoft.com would be great, but would require design of a LMS-type delivery, and I am not sure that site is the right platform.  What is your vision for course content on opensource.microsoft.com ?
> 
> thanks for the question.
> 
> 

Thank you for your answer. I was not thinking about moving the courses to opensource.microsoft.com. More copying them there. In this repo most things are written very general, which is good. But on opensource.microsoft.com we could make it company specific (with Microsofts name, etc.)

I had something very simple in mind like first you can choose the module and then there will be the lessons with simple back and fourth buttons to navigate.

**Comment by emmairwin** [comment]
That sounds great to me!

**Comment by Aaron-Junker** [comment]
> That sounds great to me!
> 

Nice to hear you agree.

**Comment by emmairwin** [comment]
Closing for now as we have no plans to have courses on the main open source site.
